### ISSUE TITLE
Release a new patch version

### ISSUE THREAD

**Issue by Michael-F-Bryan** [google/pulldown-cmark#120]
Is there any chance you could make a patch release (`0.1.1`) to crates.io? [mdbook] is currently pinned  to `master` instead of the latest version on crates.io because we use #118 internally, preventing us from doing another release (you can't have `git` dependencies when publishing to crates.io). 

[mdbook]: https://github.com/rust-lang-nursery/mdBook

**Comment by nox** [comment]
Ping on this, someone on the Rust IRC channel mentioned they would like even more types to implement `PartialEq`, `Hash` etc like in #118, but if there is no release in the end it would be quite unfortunate.

**Comment by raphlinus** [comment]
Sorry about going so long without answering. Yes, I'll do a release soon. I believe @Manishearth has another PR in the queue, but if that'll be a while, I can release off current master.
