### ISSUE TITLE
Option to insert reference link definitions on demand

### ISSUE THREAD

**Issue by killercup** [google/pulldown-cmark#121]
It would be very helpful to be able to register a callback function that is called whenever the parser encounters a reference link it doesn't have a definition for.

If I'm not mistaken, it should suffice to add a new constructor `Parse::with_ref_link_callback(text, fn)` and call `fn`, if set, here instead of returning `None` directly:

https://github.com/google/pulldown-cmark/blob/c1ac9123f1653dc774403634696f848ffecbb01c/src/parse.rs#L1301

Please let me know if this is something you want to do in this project, and what your preferred API would look like.

## Context

@QuietMisdreavus and @Manishearth are currently working on implement [Rust RFC 1946](https://github.com/rust-lang/rfcs/blob/b9b71bbddd7ae54b338e3c17f47f30b9602cc338/text/1946-intra-rustdoc-links.md) "Intra rustdoc links" in <https://github.com/rust-lang/rust/pull/47046>.

The RFC's goal is to make it easy to link to Rust items in doc comments, and the main way to do that is by adding "implied ref links": You can write a doc comment containing

> This calls [foo()] with the given [::bar::Baz].

and rustdoc will generate the correct links to the function `foo` and the type `Baz`.

Rustdoc will soon use pulldown-cmark, and our goal is to land this feature once it does. Sadly, the current API of pulldown will return links without definitions as text events, so we can't dynamically generate and add these links. Adding all link definitions up front is not viable, as there may be links to external crates, which means the number of possible definitions is infinite.

**Comment by raphlinus** [comment]
Yes, I've thought about adding a feature like this, and the API sketch you propose looks good. If the API has been considered by the rustdoc people I will very likely be ok with adding it.

I'm a bit overloaded with other things right now, but if adding this is blocking on me, feel free to ping me.

**Comment by Manishearth** [comment]
The api seems like it would fit well in rustdoc. I can do the engineering
work for this, shouldn't be hard.

We're not blocked on this right now since we need to completely finish
swapping out the old parser before we introduce pulldown-only features. So
no rush.

**Comment by Manishearth** [comment]
https://github.com/google/pulldown-cmark/pull/123
