### ISSUE TITLE
cc: error: ./specs: Is a directory

### ISSUE THREAD

**Issue by ExpHP** [google/pulldown-cmark#122]
On nightly, building a crate that depends on `pulldown-cmark` (`version-sync`, which for reference uses `default-features = false`):

```
$ rustc --version
rustc 1.25.0-nightly (ee220daca 2018-01-07)
$ cargo test --release
   Compiling unicode-normalization v0.1.5
   Compiling linked-hash-map v0.5.0
   Compiling proc-macro-hack-impl v0.4.0
   Compiling percent-encoding v1.0.1
   Compiling cc v1.0.3
   Compiling pulldown-cmark v0.1.0
   Compiling rustc-demangle v0.1.5
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/lampam/cpp/other/rust/poscar/target/release/build/pulldown-cmark-1a54e35618085403/build_script_build-1a54e35618085403.build_script_build0-4ef248cb98883e9ddfea56f256a9a112.rs.rcgu.o" "/home/lampam/cpp/other/rust/poscar/target/release/build/pulldown-cmark-1a54e35618085403/build_script_build-1a54e35618085403.build_script_build1-4ef248cb98883e9ddfea56f256a9a112.rs.rcgu.o" "-o" "/home/lampam/cpp/other/rust/poscar/target/release/build/pulldown-cmark-1a54e35618085403/build_script_build-1a54e35618085403" "/home/lampam/cpp/other/rust/poscar/target/release/build/pulldown-cmark-1a54e35618085403/build_script_build-1a54e35618085403.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/lampam/cpp/other/rust/poscar/target/release/deps" "-L" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-57c545ae25e5f13f.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a5fd2c8277898f0f.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-9237147e2fa9db81.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-2bdc4af4530767ba.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-dae6f2d47b6c3e8c.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-699c526bfb038f69.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-46020066f996da68.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-734bf5d240657dcc.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-13329002a493bf0e.rlib" "/home/lampam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-68a2b19e2f4d8004.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util""-l" "util"
  = note: cc: error: ./specs: Is a directory


error: aborting due to previous error

error: Could not compile `pulldown-cmark`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

A similar error occurs if I try `cargo install pulldown-cmark`

I am able to build it on the beta channel just fine.
(**edit:** it just occured to me while afk that I only updated the nightly channel before making this report, so this may not necessarily be true for the current beta)

Any ideas as to what could be causing this? Perhaps it is a bug in rustc?

---

Linux 4.14.10-1-ARCH

cc (GCC) 7.2.1 20171128

**Comment by myfreeweb** [comment]
Also encountered this, while trying to build `clippy` (also on Arch)

**Comment by ExpHP** [comment]
**If you are receiving this error it may due to a poorly configured environment.**

http://gcc-help.gcc.gnu.narkive.com/8AbbmxJN/specs-directory-interferes-with-the-operation-of-gcc-in-configure-scripts

### Summary

pulldown-cmark has a toplevel directory named `spec`.  A poorly configured `LIBRARY_PATH`, `LPATH` or `GCC_EXEC_PREFIX` may cause gcc to attempt to read this directory as a file.

### Test to verify that this is the cause

Do this anywhere on your system.

```rust
$ mkdir -p test/spec
$ cd test
$ gcc --version
gcc: error: ./specs: Is a directory
```
(in a correctly-configured environment, this would, of course, simply print the version)

### Solution

**Ensure that the current directory is not listed in `LIBRARY_PATH`, `LPATH`, or `GCC_EXEC_PREFIX`.**

Note that an empty entry is interpreted as the current directory, because that's how POSIX defined PATH, and POSIX hates you. **This means that these variables must not begin or end with `:`, and must not contain `::` anywhere in the middle.**

In my experience, this can easily occur as a result of the common pattern of using
```sh
export VAR=some/new/path:$VAR
```
to append paths to an environment variable without accidentally clobbering a pre-existing value. Needless to say, the very first time this is done it leaves an empty component at the end.

My suggestion is that you pick a file that you own where you modify the variable, and simply add a line to delete empty components after the fact. (this only needs to be done once, and as long as it is done at some point after the first path you add to the variable, it will work equally well regardless of whether VAR existed prior to the script)

```sh
# in e.g. .bashrc
export VAR=some/new/path:$VAR
export VAR=some/other/path:$VAR

# delete any possible empty components
VAR=$(echo $VAR | sed -E -e 's/^:*//' -e 's/:*$//' -e 's/:+/:/g')
```

**Comment by ExpHP** [comment]
Closing unless somebody can show that the above does not solve their issue.

**Comment by cbcoutinho** [comment]
I am still having this issue (caused by trying to install `clippy` using on `cargo nightly`). On a clean install of `rustup` and the `nightly` toolchain, I am also getting the same error as reported above:

```shell
$ cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing clippy v0.0.186
.
.
.
  = note: cc: error: ./specs: Is a directory
          

error: aborting due to previous error

error: Could not compile `pulldown-cmark`.
warning: build failed, waiting for other jobs to finish...
```

Adding the environmental variable line about deleting any possible empty components for my $PATH does not solve the issue.

**Comment by myfreeweb** [comment]
@cbcoutinho `LIBRARY_PATH` not `PATH`

**Comment by cbcoutinho** [comment]
My mistake, there was indeed an issue with my `LIBRARY_PATH`, and I had only looked at `PATH`. Thanks again.

**Comment by ExpHP** [comment]
Perhaps I was wrong to attribute this behavior to POSIX: (emphasis mine)

> http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html
>
>  When a non-zero-length prefix is applied to this filename, a slash shall be inserted between the prefix and the filename. A zero-length prefix is a legacy feature that indicates the current working directory. It appears as two adjacent colons ( "`::`" ), as an initial colon preceding the rest of the list, or as a trailing colon following the rest of the list. **A strictly conforming application shall use an actual pathname (such as `.`) to represent the current working directory in `PATH`.**

But in any case, I don't suppose the maintainers of GCC see this as a bug.  For some variables (though notably not all), this behavior is even documented: 

> https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html
>
> `CPATH`
> `C_INCLUDE_PATH`
> `CPLUS_INCLUDE_PATH`
> `OBJC_INCLUDE_PATH`
>
> Each variable’s value is a list of directories separated by a special character, much like PATH, in which to look for header files. The special character, PATH_SEPARATOR, is target-dependent and determined at GCC build time. For Microsoft Windows-based targets it is a semicolon, and for almost all other targets it is a colon.
>
> ...
>
> **In all these variables, an empty element instructs the compiler to search its current working directory. Empty elements can appear at the beginning or end of a path.** For instance, if the value of CPATH is :/special/include, that has the same effect as `-I. -I/special/include`.

**Comment by njaard** [comment]
@ExpHP, curiously, the gcc manual there indicates that `LIBRARY_PATH` should not have that behavior.
