### ISSUE TITLE
Unable to use Options

### ISSUE THREAD

**Issue by Alex-PK** [google/pulldown-cmark#13]
I am trying to use pulldown-cmark in my own project, and I need the tables support, so I tried to use them like in the included binary (this is the main.rs):

    extern crate pulldown_cmark;
    
    use pulldown_cmark::Parser;
    use pulldown_cmark::{Options, OPTION_ENABLE_TABLES, OPTION_ENABLE_FOOTNOTES};
    use pulldown_cmark::html;
    
    pub fn main() {
        let md = String::from("# Some markdown");
    
        let mut opts = Options::empty();
        opts.insert(OPTION_ENABLE_TABLES);
        opts.insert(OPTION_ENABLE_FOOTNOTES);
    
        let mut s = String::with_capacity(md.len() * 2);
        let p = Parser::new_ext(&md, opts);
        let p = Parser::new(&md);
    
        html::push_html(&mut s, p);
        println!("{}", s);
    }

But I get an error from the compiler:

src/main.rs:4:22: 4:29 error: unresolved import `pulldown_cmark::Options`. There is no `Options` in `pulldown_cmark` [E0432]
src/main.rs:4 use pulldown_cmark::{Options, OPTION_ENABLE_TABLES, OPTION_ENABLE_FOOTNOTES};
                                   ^~~~~~~
src/main.rs:4:22: 4:29 help: run `rustc --explain E0432` to see a detailed explanation

(Same for the 2 constants).

I can see they are re-exported but they are defined with a macro, and I am not skilled enough to debug through it.

Is this the correct way to use them?

**Comment by notriddle** [comment]
Are you using the version from Crates.IO? Because it's not in that version
yet.

**Comment by Alex-PK** [comment]
Yes, I configured it in Cargo.toml and it downloaded 0.0.3.
Thanks for this info. I managed to configure my project to look for the library locally and it compiles perfectly.
