### ISSUE TITLE
New release to crates.io?

### ISSUE THREAD

**Issue by steveklabnik** [google/pulldown-cmark#14]
There are a bunch of fixes in this repository that would be really great to have available on crates.io. Any chance we can get a new release?

**Comment by notriddle** [comment]
@raphlinus hasn't done anything with this repo since August, so I'd guess probably not.

**Comment by steveklabnik** [comment]
@raphlinus are you abandoning this project? Life happens, I totally understand :) If so, would you maybe be interested in new maintainers? I would really like to eventually get Rustdoc using this, and mdBook already does, but if it's truly abandoned, that would mean a fork, which isn't as nice :(

**Comment by raphlinus** [comment]
Sorry for being unresponsive. I fell into a period of being busy almost to the point of burnout in my day job, and set down my Rust work for the time being. It is something I'd like to pick up again, and can put some time into it this week.

For doing a quick crates.io release, what would be the most useful? Current github master, or are there some PR's that need to be merged? I hope to get through them all, but don't know how long that will take.

**Comment by steveklabnik** [comment]
I haven't looked, but I'd be happy to check them out if that's helpful. :) let me do that and i'll leave some comments :+1: 

(But yeah, seriously, I know what that's like hardcore, burnout is brutal)

**Comment by steveklabnik** [comment]
Okay! So, here's my assessment: you could just cut the current master, and that'd be fine. There's only three open PRs:

* https://github.com/google/pulldown-cmark/pull/12 I'm not sure what this does, and there's no tests, so i dunno
* https://github.com/google/pulldown-cmark/pull/11 looks great but doesn't affect the code, it's just about builds.
* https://github.com/google/pulldown-cmark/pull/3 is a larger PR with some issues around it, and so probably needs more discussion/thought before merging.

**Comment by notriddle** [comment]
#12: There should be a test added to make sure that tables can be turned
off and footnotes turned on separately. It's a copy-paste error: my bad.

**Comment by raphlinus** [comment]
Ok, I just pushed master as 0.0.5, which I hope should unblock people. Over the next few days I hope to look into the remaining open github issues, and also make sure that we track the latest changes to teh spec. That involves implementing the fancy new stack-lookahead algorithm for inline markup, which will fix [Example 434](http://spec.commonmark.org/0.23/#example-434), and also make sure that the parse time stays linear even with pathological inputs. It's tricky but the kind of thing that's fun for me - I worked out how to do it a few months ago but then didn't get around to actually coding it.

I'll close this issue as soon as people confirm that 0.0.5 is actually usable for them. If not, please update the issue with what needs fixing.

**Comment by azerupi** [comment]
Nice, thanks a lot @raphlinus I will update mdBook to use the latest version so that Steve can test it for the Rust book :)

**Comment by steveklabnik** [comment]
This issue is very out of date :+1:
