### ISSUE TITLE
`Event` should derive `Debug`

### ISSUE THREAD

**Issue by DanielKeep** [google/pulldown-cmark#2]
Currently, events can't be easily logged or printed.

**Comment by raphlinus** [comment]
I believe this is fixed by b56ad11263abcabdfcff95ae5f8356b79fdb4c5b.

**Comment by DanielKeep** [comment]
Thanks; with this, and some thinking on my end, my Markdown scraping code has gone from [40 lines using hoedown](https://github.com/DanielKeep/cargo-script/blob/2c4a5172b1b9a138d2ee831cfc5e2f1fb6168614/src/manifest.rs#L628-L668) to [20 lines using PDCM and some iterator methods](https://github.com/DanielKeep/cargo-script/blob/use-pulldown-cmark/src/manifest.rs#L628-L648).  Plus, it's now lazy, only consuming the input it needs.
