### ISSUE TITLE
Shouldn't regex-fancy have its own repository?

### ISSUE THREAD

**Issue by notriddle** [google/pulldown-cmark#22]
Why is it in here? They don't even depend on each other (and while pulldown-cmark may eventually depend on regex-fancy, I would think you'd just use Cargo to fetch it).

**Comment by Eh2406** [comment]
+1 I was looking for regex-fancy and was surprised it was not on Cargo. If you want that name grab it.

**Comment by messense** [comment]
+1 for adding fancy-regex to crates.io.
