### ISSUE TITLE
ordered lists items need item number

### ISSUE THREAD

**Issue by bestouff** [google/pulldown-cmark#25]
Ordered lists are started by a `List(Some(start))`, which is ok, but then each item is started by an `Item`, which means the item number is lost and has to be kept somewhere in a context for a renderer who would need it.
It would be helpful to replace the `Item` with an `Item(Some(n))` for ordered lists (and `Item(None)` for unordered ones).

**Comment by notriddle** [comment]
The CommonMark spec doesn't say that out-of-order list items need to be considered, only that the starting point of the list matters. [And the dingus acts the same way pulldown-cmark does](http://spec.commonmark.org/dingus/?text=4.%20item%20one%0A1.%20Item%20two%0A1.%20Item%20three)

**Comment by bestouff** [comment]
Oh no, that's just to help when doing nested ordered lists - to have the `Item` number handed by the parser.

**Comment by bestouff** [comment]
µAfter thinking a bit more about it you're probably right, this is useless; sorry for the noise.
