### ISSUE TITLE
Event clonable?

### ISSUE THREAD

**Issue by ConnyOnny** [google/pulldown-cmark#34]
Hi,

is there any reason why `Event` doesn't implement the `Clone` trait? `Tag` already does.
If `Event` would be clonable, then I could use the [tee function from itertools](https://docs.rs/itertools/*/itertools/trait.Itertools.html#method.tee) to do two things with the parsing at the same time (e.g. building an html representation AND another representation), which would be nice.

**Comment by raphlinus** [comment]
I don't think there's a specific reason for it. Cloning text events will probably cause string copying, but that's probably not a serious performance problem. Happy to accept a PR, or can do it myself when I get some time.

**Comment by ConnyOnny** [comment]
Okay I tried this: You can just `derive` it. It's a one-word fix. Can you please add it? I don't want to create a Google account for this (required to sign the CLA).

And about the string copies: I think not, because they're all in `Cow`s.
