### ISSUE TITLE
footnotes support

### ISSUE THREAD

**Issue by blaenk** [google/pulldown-cmark#4]
Not sure what your intentions are with implementing things that aren't in CommonMark, so feel free to close these if they're not relevant, though personally I'd love to see them available here.

Footnotes is a big one for me.

**Comment by raphlinus** [comment]
Yes, I intend to implement footnotes, as it's one of the requirements for rustdoc. See <https://users.rust-lang.org/t/new-commonmark-parser/1690/20> in particular. It's just a question of when I'll get to it, as I'm pretty busy these days.

**Comment by blaenk** [comment]
Great job @notriddle
